# Generated by Django 3.1.6 on 2021-02-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('categoriaId', models.AutoField(auto_created=True, db_column='categoria_id', primary_key=True, serialize=False, unique=True)),
                ('categoriaNombre', models.CharField(db_column='categoria_nombre', max_length=45)),
                ('categoriaDescripcion', models.CharField(db_column='categoria_descripcion', max_length=45)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 't_categoria',
            },
        ),
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('personaId', models.AutoField(db_column='persona_id', primary_key=True, serialize=False, unique=True)),
                ('personaCargo', models.CharField(db_column='persona_cargo', max_length=45)),
                ('personaNombre', models.CharField(db_column='persona_nombre', max_length=45)),
                ('personaDocumento', models.CharField(db_column='persona_documento', max_length=45)),
                ('personaTelefono', models.CharField(db_column='persona_Telefono', max_length=45)),
                ('personaEstado', models.CharField(db_column='persona_estado', max_length=45)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 't_persona',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('usuarioId', models.AutoField(db_column='usuario_id', primary_key=True, serialize=False, unique=True)),
                ('usuarioDocumento', models.CharField(db_column='usuario_documento', max_length=45)),
                ('usuarioCargo', models.CharField(db_column='usuario_cargo', max_length=45)),
                ('usuarioNombre', models.CharField(db_column='usuario_nombre', max_length=45)),
                ('usuarioTelefono', models.CharField(db_column='usuario_telefono', max_length=45)),
                ('usuarioUsers', models.CharField(db_column='usuario_users', max_length=45)),
                ('usuarioEstado', models.CharField(db_column='usuario_estado', max_length=45)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 't_usuario',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('productoId', models.AutoField(db_column='producto_id', primary_key=True, serialize=False, unique=True)),
                ('productoCodigo', models.CharField(db_column='producto_codigo', max_length=45)),
                ('productoNombre', models.CharField(db_column='producto_nombre', max_length=45)),
                ('productoStock', models.CharField(db_column='producto_stock', max_length=45)),
                ('productoDescripcion', models.CharField(db_column='producto_descripcion', max_length=45)),
                ('productoImagen', models.CharField(db_column='producto_imagen', max_length=45)),
                ('productoEstado', models.CharField(db_column='producto_estado', max_length=45)),
                ('productoMedida', models.CharField(db_column='producto_medida', max_length=45)),
                ('categoriaId', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='CategoriaProductos', to='administracion.categoriamodel')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 't_producto',
            },
        ),
        migrations.CreateModel(
            name='MovimientoModel',
            fields=[
                ('movimientoId', models.AutoField(db_column='movimiento_id', primary_key=True, serialize=False, unique=True)),
                ('movimientoTipo', models.CharField(db_column='movimiento_tipo', max_length=45)),
                ('movimientoCantidad', models.IntegerField(db_column='movimiento_cantidad')),
                ('movimientoFecha', models.DateTimeField(db_column='movimiento_fecha')),
                ('personaId', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.PROTECT, related_name='PersonaMovimiento', to='administracion.personamodel')),
                ('usuarioId', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioMovimiento', to='administracion.usuariomodel')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 't_movimiento',
            },
        ),
    ]
