# Generated by Django 3.1.6 on 2021-02-12 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomodel',
            name='productoId',
            field=models.ForeignKey(db_column='producto_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ProductoMovimiento', to='administracion.productomodel'),
            preserve_default=False,
        ),
    ]
