# Generated by Django 3.1.6 on 2021-02-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_movimientomodel_productoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomodel',
            name='productoCodigo',
        ),
    ]
