# Generated by Django 3.1.6 on 2021-02-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_productomodel_productocodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='productoEstado',
            field=models.BooleanField(db_column='producto_estado', default=True),
        ),
    ]
