# Generated by Django 3.1.6 on 2021-02-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20210213_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamodel',
            name='categoriaEstado',
            field=models.BooleanField(db_column='categoria_estado', default=True),
        ),
    ]
