# Generated by Django 3.1.6 on 2021-03-09 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20210214_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='fecCreacion', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientomodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='fecActualizacion'),
        ),
    ]
