# Generated by Django 3.1.6 on 2021-03-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20210308_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientomodel',
            name='personaId',
        ),
        migrations.RemoveField(
            model_name='productomodel',
            name='productoImagen',
        ),
    ]
